version: '3.1'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    expose:
      - 3306

  pma:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 3333:80
    volumes:
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      PMA_ARBITRARY: 1

